bills/config/routes.rb
Rails.application.routes.draw do
  root "homepages#index"

  resources :bills
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bills/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bills/app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user

  def amount=(input)
    self.amount_in_cents = input.to_f * 100
  end

  def amount
    self.amount_in_cents.to_f / 100.0
  end
end

bills/app/models/user.rb
class User < ApplicationRecord
  has_many :bills
  def password
    @_password ||= BCrypt::Password.new(password_hash)
  end

  def password=(unhashed_password)
    @_password = BCrypt::Password.create(unhashed_password)
    self.password_hash = @_password
  end

  def full_name
    # self.first_name + " " + self.last_name
    [first_name, last_name].join(" ")
  end
end

bills/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    User.find_by(id: session["current_user_id"])
  end
end

bills/app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def index
    @bills = Bill.all
    render :index
  end

  def new
    @bill = Bill.new(user_id: current_user.id, amount: 0)
  end

  def create
    # Will call setter for each of the hash key value pairs.
    @bill = Bill.new(bill_params)

    if @bill.save
      redirect_to bills_path
    else
      render :new
    end
  end

  def show
    @bill = Bill.find(params["id"])
    render :show
  end

  def destroy
    @bill = Bill.find(params["id"])
    @bill.destroy
    redirect_to bills_path
  end

  def bill_params
    # Whitelist params
    # Returns a hash with only the keys listed in the permit method.
    params.require(:bill).permit(:title, :bill_type, :amount, :user_id)
  end
end

bills/app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  layout "home"
  def index
  end
end

bills/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "home"
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.password == params[:password]
      session["current_user_id"] = @user.id
      redirect_to bills_path
    else
      @message = "Wrong username or password"
      render :new
    end
  end

  def destroy
    session.delete("current_user_id")
    redirect_to root_path
  end
end

bills/app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "home"
  def new
    @user =User.new()
  end

  def create
    @user = User.new(user_params)
    session["message"] = "you signed up!"
    if @user.save
      session["current_user_id"] = @user.id
      redirect_to bills_path
    else
      render :new
    end
  end



  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password)
  end
end

bills/app/helpers/application_helper.rb
module ApplicationHelper
end

bills/app/helpers/bills_helper.rb
module BillsHelper
end

bills/app/helpers/homepages_helper.rb
module HomepagesHelper
end

bills/app/helpers/sessions_helper.rb
module SessionsHelper
end

bills/app/helpers/users_helper.rb
module UsersHelper
end

bills/app/views/bills/index.html.erb
<h1>Split your Expenses</h1>

<%= link_to "Add an Expense", new_bill_path, class: "btn btn-primary" %>

<hr>

<div class = "row content">
  <div class = "col-md-3">
    Name
  </div>
  <div class="col-md-3">
    Type
  </div>
  <div <div class="col-md-3">
    Created By
  </div>
  <div <div class="col-md-3">
    Options
  </div>
</div>

<hr>

<% @bills.each do |bill| %>
<div class = "row content">
  <div class = "col-md-3">
    <%= link_to bill.amount, bill_path(bill.id) %>
  </div>
  <div class="col-md-3">
    <%= bill.bill_type %>
  </div>
  <div <div class="col-md-3">
    <%= bill.user.full_name%>
  </div>
  <div class="col-md-3">
    <%= link_to "Delete", bill_path(bill.id), method: :delete, class: "btn btn-danger btn-xs"%>
  </div>
</div>
<% end %>

bills/app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= link_to "Home Page", bills_path %>

<% @bill.errors.full_messages.each do |error| %>
  <%= error %>
<% end %>

<%= form_for @bill do |f| %>

  <%= f.label :bill_type %>
  <%= f.select :bill_type, ["Restaurant", "Other"] %>

  <%= f.label :amount %>
  <%= f.text_field :amount, class: 'form-control' %>

  <%= f.hidden_field :user_id,  class: 'form-control' %>

  <%= f.submit class: "btn btn-primary"%>

<% end %>

bills/app/views/bills/show.html.erb
<h1>Split your Expenses</h1>

<%= link_to "Go Back", bills_path %>

<hr>

<div class = "row content">
  <div class = "col-md-4">
    Name
  </div>
  <div class="col-md-4">
    Type
  </div>
  <div <div class="col-md-4">
    Created By
  </div>
</div>

<hr>
<div class = "row content">
  <div class = "col-md-4">
    <%= @bill.amount %>
  </div>
  <div class="col-md-4">
    <%= @bill.bill_type %>
  </div>
  <div <div class="col-md-4">
    <%= @bill.user.full_name %>
  </div>
</div>

bills/app/views/homepages/index.html.erb
<body>

  <div class="container">
      <ul class="nav navbar-nav">
          <li><%= link_to "Log In", new_session_path %></li>
          <li><%= link_to "Sign Up!", new_user_path %></li>
      </ul>
  </div>

</body>

bills/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bills</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <nav class='navbar navbar-default'>
        <ul class="nav navbar-nav">
          <% if current_user %>
            <p class="navbar-text navbar-right">Signed in as <%= current_user.full_name %></p>
            <li><%= link_to "Log out", session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log in", new_session_path %></li>
          <% end %>
        </ul>
      </nav>
      <%= yield %>
    </div>

  </body>
</html>

bills/app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forgeddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>

      <%= yield %>

  </body>
</html>

bills/app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= form_for @user do |f| %>

<%= f.label :first_name %>
<%= f.text_field :first_name, class: 'form-control' %>

<%= f.label :last_name %>
<%= f.text_field :last_name, class: 'form-control' %>

<%= f.label :email %>
<%= f.text_field :email, class: 'form-control' %>

<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>

<hr>

<%= f.submit class: 'btn btn-primary' %>
<% end %>

<br>

<p>
  <%= link_to "Welcome Page", root_path %>
</p>